name: app_position
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+8 # Camera package
  google_mlkit_pose_detection: ^0.10.0 # Pose detection
  path_provider: ^2.1.1 # File path
  wakelock: ^0.6.2 # WakeLock
  flutter_tts: ^3.8.5 # TTS (Text to Speech)
  provider: ^6.1.1 # Provider for state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
